### PR TITLE
list_files_in_directory() should be able to only return images

### PR DESCRIPTION
**Pull request by cvondrick**
Since this is a computer vision toolkit, list_files_in_directory() should be able to only return images. This commit introduces an optional parameter that:
- if it is a cell array, only return files with extensions in this arra
- if it is the string 'images', only return images  
- if it is the string 'videos', only return videos  
- if it is a string, only return files with this extension  
- if it is not given, return all files  

(Also, I wanted to see what 'pull request' did)

### CODE REVIEW

**Comment by quantombone** [comment]
Good idea on using the github system to push changes to submodules.

**Comment by quantombone** [comment]
I agree with the changes, let me pull it on my end too.

**Comment by cvondrick** [comment]
Oops, just realized that we both added the same feature here. I guess my submodule copy did not update properly. I'm not sure which solution is better -- regex or a more explicit extension enumeration.

**Comment by quantombone** [comment]
hmm, let me see what sort of conflicts my local version sees

**Comment by quantombone** [comment]
I'm not sure how your version is supposed to work...

**Comment by quantombone** [comment]
I see now, I will update comment.

**Comment by quantombone** [comment]
I just updated the comment once I figured out how to use it, I was specifying 'jpg' for the extension, but it only works with '.jpg'.

The comment can be seen here:
https://github.com/quantombone/exemplarsvm/blob/master/util/list_files_in_directory.m

**Comment by cvondrick** [comment]
Cool, looks good!

**Pull request merged**
